name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build

      - name: Start services
        run: docker compose up -d

      - name: Health check
        run: curl http://localhost:5000

      - name: Stop
        run: docker compose down
